"""empty message

Revision ID: 02be35064c80
Revises: 2ae70a479b93
Create Date: 2024-12-04 22:59:34.918578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02be35064c80'
down_revision = '2ae70a479b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_like_liked_at'), ['liked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_liked_at'))
        batch_op.drop_column('liked_at')

    # ### end Alembic commands ###
