"""empty message

Revision ID: 17379192977e
Revises: c155ecc2196f
Create Date: 2024-12-04 18:51:58.442224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17379192977e'
down_revision = 'c155ecc2196f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_post_posted_at'), ['posted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_posted_at'))
        batch_op.alter_column('body',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('posted_at')

    # ### end Alembic commands ###
